Repository MinnPost/object-sync-for-salesforce, pull requests merged in 2019-09, with the labels that each got.

#293 Unify push success hook parameters
  classes/salesforce_push.php
  docs/extending-before-and-after-saving.md
Labels: bug fix

#295 Provide an optional setting for how many log entries to clear
  classes/admin.php
  classes/logging.php
Labels: feature

#297 Fix picklist error logging
  classes/wordpress.php
Labels: bug fix

#310 Adding object type to wordpress_object_data filter
  classes/wordpress.php
  docs/extending-mapping-options.md
Labels: for developers

#312 When a fieldmap doesn't allow an operation, log it as a notice instead of an error
  classes/salesforce_push.php
Labels: chore

#313 use the log entry status variable in the title of all the log entries
  classes/salesforce.php
  classes/salesforce_mapping.php
  classes/salesforce_pull.php
  classes/salesforce_push.php
  classes/wordpress.php
Labels: chore

#315 Fix the object_sync_for_salesforce_pull_query_modify filter to prevent redundant elements
  classes/salesforce_pull.php
  docs/extending-pull.md
Labels: bug fix, for developers

#316 Stop Travis builds from failing
  .travis.yml
  composer.json
  composer.lock
Labels: for developers
